name: 'Build project'

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: cmake -B build -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=OFF -DWITH_GTEST=OFF
      - run: cmake --build build
