name: "Validate and Build"

on:
  push:
    branches:
      - masters
      - "hw*/*"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  build:
    needs: lint
    uses: ./.github/workflows/build.yml

  test:
    if: true
    needs: build
    uses: ./.github/workflows/tests.yml

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      package_name: hw2-ip-filter
    permissions:
      contents: write
