name: 'Validate and Build'

on:
  push:
    branches:
      - master
      - 'hw*/*'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  build:
    needs: lint
    uses: ./.github/workflows/build.yml

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      package_name: hw1-setup-ci
    permissions:
      contents: write