name: 'Release'

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON
      - run: cmake --build .
      - run: cmake --build . --target package
      - name: Set package filename
        id: pkg
        run: |
          SRC=$(ls *.deb)
          DST="${{ inputs.package_name }}-${{ github.ref_name }}-${{ github.run_number }}.deb"
          mv "$SRC" "$DST"
          echo "FILE=$DST" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.pkg.outputs.FILE }}
          asset_name: ${{ steps.pkg.outputs.FILE }}
          asset_content_type: application/vnd.debian.binary-package
